# Here, the application is defined as a service called "server".
# This service is built from the Dockerfile in the current directory.
services:
  server:
    image: hienng/cupboard_mobile_webapp:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    build: .
