name: Deploy to Vercel on Release

on:
  release:
    types: [published]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log Event Context
        run: |
          echo "The workflow was triggered by the following event:"
          echo "${{ toJson(github) }}"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Get existing deployments
        id: get_deployments
        run: |
          deployments=$(vercel deployments ls --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "Deployments: $deployments"
          echo "::set-output name=deployments::$deployments"

      - name: Delete old deployment if exists
        if: steps.get_deployments.outputs.deployments != ''
        run: |
          old_deployment_id=$(echo "${{ steps.get_deployments.outputs.deployments }}" | grep -oP '^\S+' | head -n 1)
          echo "Deleting old deployment with ID: $old_deployment_id"
          vercel rm $old_deployment_id --yes --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
