name: Link Branch to Linear Issue

on:
  create:
    branches:
      - '*'

jobs:
  link-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract issue number from branch name
      id: extract
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        echo "Branch name: $BRANCH_NAME"
        
        # Define regex pattern to match the naming convention
        PATTERN='^[a-zA-Z0-9._-]+/([0-9]+)-[a-zA-Z0-9._-]+$'

        if [[ "$BRANCH_NAME" =~ $PATTERN ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[1]}"
          echo "Issue number: $ISSUE_NUMBER"
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
        else
          echo "Branch name does not match the expected format."
          echo "Expected format: username/identifier-title"
          exit 1
        fi

    - name: Add comment to Linear issue
      env:
        LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
      run: |
        if [ -z "$ISSUE_NUMBER" ]; then
          echo "No issue number found."
          exit 1
        fi
        
        # Construct the branch URL
        BRANCH_URL="https://github.com/COMP4350-Team2/${{ github.event.repository.name }}/branches/${GITHUB_REF#refs/heads/}"
        COMMENT="Branch ${GITHUB_REF#refs/heads/} has been created for this issue. You can view it [here](${BRANCH_URL})."

        echo "Adding comment to Linear issue with number $ISSUE_NUMBER..."

        # Add a comment to the Linear issue using Linear API
        comment_response=$(curl -s -o comment_response.json -w "%{http_code}" -X POST https://api.linear.app/graphql \
          -H "Authorization: Bearer $LINEAR_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "query": "mutation { commentCreate(input: { issueId: \"'$ISSUE_NUMBER'\", body: \"'$COMMENT'\" }) { comment { id } } }"
          }')

        echo "Comment creation response: $comment_response"
        cat comment_response.json

        if [ "$(echo $comment_response | grep -o '"id":' | wc -l)" -eq 0 ]; then
          echo "Error adding comment to issue. Response code: $response"
          exit 1
        else
          echo "Comment added successfully."
        fi
