name: mobile_ci

on:
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

  release:
    types: [published]

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/cupboard_mobile_webapp:latest

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up environment file
        env:
          ENV_FILE: ${{ secrets.ENV }}
        run: echo "$ENV_FILE" > ".env"

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Delete previous node modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Clear ESLint cache
        run: rm -f .eslintcache

      - name: Clean TypeScript cache
        run: rm -rf ./node_modules/.cache/typescript

      - name: Start application
        run: npm run build

  Build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare build
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
