name: mobile_ci

on:
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

  release:
    types: [published]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up environment file
        env:
          ENV_FILE: ${{ secrets.ENV }}
        run: echo "$ENV_FILE" > ".env"

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm run build

  Build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/cupboard_mobile_webapp:latest
